#!/bin/sh

# https://www.topbug.net/blog/2012/03/17/generate-ctags-files-for-c-slash-c-plus-plus-source-files-and-all-of-their-included-header-files/
# ./ctags_with_dep.sh <includes files> ... to generate a tags file for these files.
#<includes file> is generated by running gcc with -M option

cat $@ | sed -e 's/[\\ ]/\n/g' | \
  sed -e '/^$/d' -e '/\.o:[ \t]*$/d' | \
  ctags -L -
